name: Save Traefik Image

on:
  workflow_dispatch:

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Pull amd64 image
        run: docker pull --platform linux/amd64 traefik:v3.6       

      - name: Save image
        run: docker save traefik:v3.6 | gzip > traefik-v3.6-amd64.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: traefik-v3.6-amd64
          path: traefik-v3.6-amd64.tar.gz
